package jn.mjz.aiot.jnuetc.kotlin.model.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jn.mjz.aiot.jnuetc.kotlin.model.entity.Data;
import jn.mjz.aiot.jnuetc.kotlin.model.entity.DataChangeLog;

import jn.mjz.aiot.jnuetc.kotlin.model.greendao.DataDao;
import jn.mjz.aiot.jnuetc.kotlin.model.greendao.DataChangeLogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataDaoConfig;
    private final DaoConfig dataChangeLogDaoConfig;

    private final DataDao dataDao;
    private final DataChangeLogDao dataChangeLogDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataDaoConfig = daoConfigMap.get(DataDao.class).clone();
        dataDaoConfig.initIdentityScope(type);

        dataChangeLogDaoConfig = daoConfigMap.get(DataChangeLogDao.class).clone();
        dataChangeLogDaoConfig.initIdentityScope(type);

        dataDao = new DataDao(dataDaoConfig, this);
        dataChangeLogDao = new DataChangeLogDao(dataChangeLogDaoConfig, this);

        registerDao(Data.class, dataDao);
        registerDao(DataChangeLog.class, dataChangeLogDao);
    }
    
    public void clear() {
        dataDaoConfig.clearIdentityScope();
        dataChangeLogDaoConfig.clearIdentityScope();
    }

    public DataDao getDataDao() {
        return dataDao;
    }

    public DataChangeLogDao getDataChangeLogDao() {
        return dataChangeLogDao;
    }

}
